version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - gis_2ban_network
    volumes:
      - media:/data/media/
      - static:/data/static/
      - gis_log:/var/log/nginx/
      - /home/loooooky1234/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - mode: host
        protocol: tcp
        target: 80
        published: 80

  goaccess:
    image: allinurl/goaccess:1.5.1
    volumes:
      - gis_log:/var/log/nginx
    ports:
      - 7890:7890
    command: /var/log/nginx/gis_access.log -o /var/log/nginx/report.html --log-format=COMBINED --real-time-html

  django:
    image: gis_test_image:5
    networks:
      - gis_2ban_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - media:/home/gis_project/media/
      - static:/home/gis_project/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_2ban_network
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gis_2ban_network:

volumes:
  media:
  static:
  mariadb:
  gis_log:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true